### ISSUE TITLE
Make redirect URLs case sensitive

### ISSUE THREAD

**Issue by paulinebessoles** [decidim-ice/decidim-module-decidim_awesome#188]
**Is your feature request related to a problem? Please describe.**
As an admin, when I want to update an attachment, it's URL changes, which renders all the links I made to the attachment obsolete (in content or newsletters). 
I tried to use custom redirections to allow but the destination field is not case sensitive and downcases the URL, so the redirection leads to a 404. 

**Describe the solution you'd like**
I'd like the destination field to take into account capital letters. 

**Describe alternatives you've considered**
Develop a feature for attachments permalinks in decidim core.

**Additional context**
<img width="1057" alt="Capture d’écran 2022-07-08 à 17 33 06" src="https://user-images.githubusercontent.com/52420208/178024228-fe39e5ba-4480-4481-bd2f-97314674b8d8.png">
<img width="1068" alt="Capture d’écran 2022-07-08 à 17 33 15" src="https://user-images.githubusercontent.com/52420208/178024224-4b8f39ab-37e0-4b8c-9f8b-7a26f6b1343c.png">

If anyone thought about another solution for this attachment URL issue, I'm all ears! 😃

**Comment by microstudi** [comment]
@paulinebessoles I think this is a good think to have. As awesome is already on ICE, do you think OSP can make a PR with this little change? should be easy

**Comment by paulinebessoles** [comment]
Hi @microstudi, we don't have the ressources right now to send a PR, but I keep it in mind for when we have some time!

**Comment by paulinebessoles** [comment]
I close this issue, as it is also reported here: https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/239
