### ISSUE TITLE
Error 500 after Install on 0.26

### ISSUE THREAD

**Issue by flogee** [decidim-ice/decidim-module-decidim_awesome#190]
Hi i just tried to install your module, but after following the install steps on our 0.26 instance, some error appeared. Maybe you can give me a hint? See Log below. Thanks!

1. put gem "decidim-decidim_awesome" into the gemfile
2. bundle
3. bundle exec rails decidim_decidim_awesome:install:migrations
4. bundle exec rails decidim_decidim_awesome:webpacker:install
5. bundle exec rails db:migrate

Decidim-Log-Output:

I, [2022-08-12T14:09:38.778982 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc] Processing by Decidim::ErrorsController#internal_server_error as HTML
D, [2022-08-12T14:09:38.780618 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[36mCACHE Decidim::ImpersonationLog Load (0.0ms)[0m  [1m[34mSELECT "decidim_impersonation_logs".* FROM "decidim_impersonation_logs" WHERE "decidim_impersonation_logs"."decidim_admin_id" = $1 AND "decidim_impersonation_logs"."ended_at" IS NULL AND "decidim_impersonation_logs"."expired_at" IS NULL ORDER BY "decidim_impersonation_logs"."id" ASC LIMIT $2[0m  [["decidim_admin_id", 6], ["LIMIT", 1]]
D, [2022-08-12T14:09:38.781832 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[36mCACHE Decidim::ImpersonationLog Load (0.0ms)[0m  [1m[34mSELECT "decidim_impersonation_logs".* FROM "decidim_impersonation_logs" WHERE "decidim_impersonation_logs"."decidim_admin_id" = $1 AND "decidim_impersonation_logs"."ended_at" IS NULL AND "decidim_impersonation_logs"."expired_at" IS NOT NULL ORDER BY "decidim_impersonation_logs"."id" ASC LIMIT $2[0m  [["decidim_admin_id", 6], ["LIMIT", 1]]
D, [2022-08-12T14:09:38.783060 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[35mCACHE  (0.0ms)[0m  [1m[34mSELECT CONCAT('/pages/', slug) FROM "decidim_static_pages" WHERE "decidim_static_pages"."decidim_organization_id" = $1 AND "decidim_static_pages"."allow_public_access" = $2 ORDER BY "decidim_static_pages"."weight" ASC[0m  [["decidim_organization_id", 4], ["allow_public_access", true]]
I, [2022-08-12T14:09:38.789639 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendering /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-core-0.26.0/app/views/decidim/errors/internal_server_error.html.erb within layouts/decidim/application
I, [2022-08-12T14:09:38.790709 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendered /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-core-0.26.0/app/views/decidim/errors/internal_server_error.html.erb within layouts/decidim/application (Duration: 0.9ms | Allocations: 193)
D, [2022-08-12T14:09:38.792982 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[36mCACHE Decidim::ContentBlock Load (0.0ms)[0m  [1m[34mSELECT "decidim_content_blocks".* FROM "decidim_content_blocks" WHERE "decidim_content_blocks"."published_at" IS NOT NULL AND "decidim_content_blocks"."decidim_organization_id" = $1 AND "decidim_content_blocks"."scope_name" = $2 AND "decidim_content_blocks"."manifest_name" = $3 LIMIT $4[0m  [["decidim_organization_id", 4], ["scope_name", "homepage"], ["manifest_name", "hero"], ["LIMIT", 1]]
D, [2022-08-12T14:09:38.794316 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[36mCACHE Decidim::ContentBlockAttachment Load (0.0ms)[0m  [1m[34mSELECT "decidim_content_block_attachments".* FROM "decidim_content_block_attachments" WHERE "decidim_content_block_attachments"."decidim_content_block_id" = $1 AND "decidim_content_block_attachments"."name" = $2 LIMIT $3[0m  [["decidim_content_block_id", 25], ["name", "background_image"], ["LIMIT", 1]]
D, [2022-08-12T14:09:38.797126 #2050564] DEBUG -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   [1m[36mCACHE ActiveStorage::Attachment Load (0.0ms)[0m  [1m[34mSELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4[0m  [["record_id", 4], ["record_type", "Decidim::ContentBlockAttachment"], ["name", "file"], ["LIMIT", 1]]
I, [2022-08-12T14:09:38.797438 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendered /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-core-0.26.0/app/views/layouts/decidim/_meta_tags_config.html.erb (Duration: 5.9ms | Allocations: 1706)
I, [2022-08-12T14:09:38.799829 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendered /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-decidim_awesome-0.8.3/app/views/v0.26/layouts/decidim/_head.html.erb (Duration: 2.1ms | Allocations: 617)
I, [2022-08-12T14:09:38.799922 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendered /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-decidim_awesome-0.8.3/app/views/layouts/decidim/_head.html.erb (Duration: 2.3ms | Allocations: 682)
I, [2022-08-12T14:09:38.799961 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc]   Rendered /home/admin/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/decidim-core-0.26.0/app/views/layouts/decidim/_application.html.erb (Duration: 8.8ms | Allocations: 2646)
I, [2022-08-12T14:09:38.800316 #2050564]  INFO -- : [1c1bd724-855f-4cfb-9190-f5e5138e40bc] Completed 500 Internal Server Error in 21ms (ActiveRecord: 0.1ms | Allocations: 9197)

**Comment by pirimpompito** [comment]
Don't know if this is your case but I had to do `rails assets:precompile` for it to work
