### ISSUE TITLE
Decidim 0.27 compatibility

### ISSUE THREAD

**Issue by arusa** [decidim-ice/decidim-module-decidim_awesome#196]
I have installed a first decidim 0.27 instance and found out that decidim_awesome is restricted to <0.27.

I can't find anything about 0.27 compatibility. Are there any plans?
Has anyone tried decidim_awesome with 0.27?

I'm thinking about forking and testing it ;-)

**Comment by paulinebessoles** [comment]
Same here, @microstudi do you plan to upgrade awesome in the following weeks? Best 😙

**Comment by paarals** [comment]
Hi @paulinebessoles and @arusa, we are planning to do this upgrade this week. sorry for the delay! 
cc/ @microstudi

**Comment by microstudi** [comment]
Yes, happy to announce that Decidim Awesome is going to have some new cool new features as well! stay tuned!  🤪

**Comment by paulinebessoles** [comment]
Awesome, can't wait to see what's coming 😍

**Comment by arusa** [comment]
Hey @paarals! Nice to hear. Meanwhile I have forked and created a branch that seems to work with 0.27, but we didn't do a lot of tests yet.

I'll link my branch here, but it sounds like you don't need it anymore ;-)

https://github.com/DecidimAustria/decidim-module-decidim_awesome/tree/update-to-decidim-0.27

**Comment by microstudi** [comment]
Thanks @arusa I appreciate this. If you want, create a PR, it will need some additions (I'll remove the rectify dependency), but it's a start. In fact, if you give me permission to your repo I can make the rest of the changes on your branch so your contribution will be maintained.

**Comment by arusa** [comment]
Thanks @microstudi, I gave you write access to our repo and created a PR. Use whatever you need ;-)

**Comment by microstudi** [comment]
I'll close this issue since #202 is merged.

**Comment by arusa** [comment]
@microstudi thanks for updating our repo. Unfortunately it broke the "Awesome Map". After your changes it only showed the whole world and the browser console showed the JS error, that it couldn't load jQuery

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/623008/214432144-5fcdbd63-df17-400e-b403-719dbb28a9ac.png">

<img width="920" alt="image" src="https://user-images.githubusercontent.com/623008/214432212-79f50920-27e0-4f81-89d5-3e70caba945a.png">

After reverting our Gemfile back to my last commit the map is zoomed in again:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/623008/214432372-68fb0064-9835-4fad-a4e8-bf99a565d1ac.png">

But I just realized, that the browser console also displayed some errors:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/623008/214432468-b1712d47-ae1c-4fa1-996d-703ef7714079.png">

**Comment by microstudi** [comment]
@arusa can you open a new issue with this? otherwise is going to be too much hidden here.
Thanks!
