### ISSUE TITLE
Admin accountability log

### ISSUE THREAD

**Issue by microstudi** [decidim-ice/decidim-module-decidim_awesome#201]
**Requirement:**

As a platform-admin I would like to be able to get an excel list with information about the assembly- and process-admins at any given date and time. The list should include name, e-mail address and according assembly / process (must). Additionally the belonging filter criteria (scope type, assembly type) (nice to have).

Important: As data about the admins should not reach the public, please describe the security measures you would implement in order not to create a target point for hackers.

**Implementation**

Add an admin controller and views where to see the historic of admins (or any other semi-admin role) that at any  given period of time. For this, this admin page would provide a specific range of dates where to filter who was admin of what. (see attached mockup)
The results will show a list of admins and their current status on the platform (if it is still active for instance), and what was administrating
 We propose to call this section in the admin "Admin accountability" (see attached mockup)
A part from the range filter, a standard filter would be added that will allow to filter per: Participatory space, scope and others (to be discussed in an agile approach)

A button to export the current search as CSV/Excel. This would work similar as other export places where the admin receives an email with the exported data in a password protected ZIP.

**Implementation details:**

We will implement this historic search of admins by using the ActionLog, a table that registers every change created in decidim. This would allow to access information about admins that were active in the past but are not longer active at the present.

**Security measures:**

The security would match standard Decidim admin security, as the controller for this section would be in the admin, only full-featured admins would be able to access it (not private-spaces admins).
Additionally, the exported CSV will be compressed in a ZIP with password protection. This is similar as currently sensitive data exports already existing in Decidim.

**Comment by paarals** [comment]
closed by #208
