### ISSUE TITLE
Awesome Map broken with latest commits

### ISSUE THREAD

**Issue by arusa** [decidim-ice/decidim-module-decidim_awesome#205]
Since the commits, that make the module compatible to Decidim 0.27, the "Awesome Map" is broken. It only shows the whole world map (fully zoomed out) and the browser console shows a JS error.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/623008/215547855-31308c29-6a45-49cc-9b74-1fc2e3d146a0.png">

<img width="920" alt="image" src="https://user-images.githubusercontent.com/623008/215270962-b0866a8c-3441-4a23-8ddb-7e1d703248dc.png">

After reverting our Gemfile back to my last commit the map is zoomed in again:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/623008/215270967-c769af40-1887-44cd-af9d-cfb1bedf0b13.png">

But I realized, that the browser console also displays some errors with this version:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/623008/215271018-5507bc9f-429a-46c7-a32c-042f628de003.png">

I am running Decidim 0.27.0 and decidim_awesome on commit https://github.com/decidim-ice/decidim-module-decidim_awesome/commit/0812def43ad828735bee7a86e338cfebf4a63630

I tested it using:

 - OS: MacOS 13.2
 - Browser Safari 16.3

**Comment by microstudi** [comment]
is this a production server? or a development instance?

**Comment by arusa** [comment]
It's on a staging instance of a new platform that hasn't been released to production yet.

**Comment by microstudi** [comment]
So far, I'm been unable to replicate this. Could it be that you have to remove the `public/decidim-packs` folder and run `assets:precompile` again?
I did found some issues with the awesome map, but they weren't the ones you are reporting. #206

**Comment by arusa** [comment]
Thanks for your update. I deploy using git push to dokku (herokuish) and public/decidim-packs is in .gitignore. So it gets rebuilt on every deploy.

I'll try it again with the latest updates and see if the errors still happen and if I can fix them.

**Comment by arusa** [comment]
I tried to test the latest decidim_awesome updates, but assets:precompile fails because src/decidim/editor/clipboard_override doesn't exist in decidim 0.27.0, but only starting in 0.27.1

clipboard_override is referenced in [app/packs/src/decidim/decidim_awesome/editors/editor.js)](https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/main/app/packs/src/decidim/decidim_awesome/editors/editor.js#L16)

I have to check if some bugs were already fixed in 0.27.1 or 0.27.2 before updating...

**Comment by microstudi** [comment]
thanks, not sure if it is worth it to make it work with 27.0 though...
