### ISSUE TITLE
Language file for FormBuilder is loaded from CDN

### ISSUE THREAD

**Issue by PierreMesure** [decidim-ice/decidim-module-decidim_awesome#217]
**Describe the bug**

For each page load of the platform (starting with the homepage), a call is made to the following address:
`https://cdn.jsdelivr.net/npm/formbuilder-languages@1.1.0/en-US.lang`

It seems to come from this [line of code](https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/a5fb3423cb09379e2cbf40e001e44325834b31c2/app/packs/src/decidim/decidim_awesome/admin/custom_fields_builder.js#L16).

**To Reproduce**
1. Go to the homepage
2. Check the network tab of your Developer tools
3. See error the faulty call

**Expected behavior**

This is an issue as with most CDN since they load their files from servers in third countries and are almost always American companies. In this specific case, my test returned Cloudflare and California. So not GDPR-friendly.

If needed, this file should be loaded from the server. It's only 3kb. It might also be an error since I'm not sure that specific file is needed at all time.

**More info (please complete the following information):**
- Decidim 0.26.5
- Decidim Awesome 0.9.1
- Example instance: [escolaipau.org](https://escolaipau.org)

**Comment by microstudi** [comment]
Yeah, I can see the value on have all the downloads in-house but, honestly I don't see it as a big deal.

Can you elaborate why is not GDPR friendly? It is not using cookies or moving data in any sense...

**Comment by PierreMesure** [comment]
Not sure how detailed I should be, do you know about the Schrems II judgement? Since IP adress is PII, even a minimal service such as a CDN can be used to track people and we know since Snowden that the US government does that in a systematic way. So all these services are forbidden according to GDPR: Google Fonts, Cloudflare, etc...

**Comment by froger** [comment]
Hello, seems there is a config to load language files from local. I guess we could add the files in the public directory and define the formbuilder config i18n.location.

https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/docs/development.md#languages

**Comment by microstudi** [comment]
> Hello, seems there is a config to load language files from local. I guess we could add the files in the public directory and define the formbuilder config i18n.location.
> 
> https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/docs/development.md#languages

I'm sure it isn't much difficult to do this. PRs welcomed!

**Comment by PierreMesure** [comment]
Happy to send it, but I'm unsure where to add these `.lang` files. Maybe `public/formbuilder/lang`?
