### ISSUE TITLE
Translating awesome proposals custom fields

### ISSUE THREAD

**Issue by esdrasitq** [decidim-ice/decidim-module-decidim_awesome#221]
**Is your feature request related to a problem? Please describe.**
Hi,
Does anyone know how to translate the proposal custom fields? 
After some investiguations I find that those  fields are rendering in a json var. But it's hard for me to add the key in the fr.yml.

![image](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/91143396/50453619-5f4f-4742-847d-7929afa988f4)

**Describe the solution you'd like**
Translate the #{var} in this file below: 

https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/main/app/views/decidim/decidim_awesome/admin/config/_autoedit_box_label.html.erb#L2

**Describe alternatives you've considered**
In the screenshot below, this is the way I try to add it in the file, but it does'nt work.

![image](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/91143396/0f313d9f-0899-4b87-bb6c-483715949861)

Any help will be appreciated, thanks.

**Comment by froger** [comment]
Hello, sorry to tell but this one will be very hard to implement. 
The [javascript library used behind the scene](https://formbuilder.online) doesn't have the functionality for translated labels. 

There is [a very old issue](https://github.com/kevinchappell/formBuilder/issues/335) existing, but unactive. From my understanding, the data-model behind the library wasn't prepared to have translated labels at all.
