### ISSUE TITLE
Upgrade to 0.28 - Admin front updates

### ISSUE THREAD

**Issue by entantoencuanto** [decidim-ice/decidim-module-decidim_awesome#257]
Related to #251

There are some pending changes (there are some more detailed tasks pending to be included in this list):
* [x] Adapt the layout to display the forms, fields and buttons like in the rest of the modules
* [x] Update the JS which refresh dynamically the content of the constraints new and edit modals changing the selected options
* [x] Recover codemirror to edit CSS boxes
* [x] Use tomselect on the multiple select ussed to assign scoped admins

**Comment by aramollis** [comment]
Maybe we can close this issue, right? @microstudi

**Comment by microstudi** [comment]
Yep!
