### ISSUE TITLE
v.0.28 / Some options to sort the list of proposals have disappeared.

### ISSUE THREAD

**Issue by aramollis** [decidim-ice/decidim-module-decidim_awesome#293]
**Describe the bug**
By default in proposal component settings you can define to sort proposal by recent first (as you can see in try.decidim.org):
<img width="1132" alt="Captura de Pantalla 2024-04-11 a les 11 02 29" src="https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/109797/2e4254db-a31a-4f28-963e-198b113e952a">

But when Awesome is installed, those options disappear:
<img width="1148" alt="Captura de Pantalla 2024-04-11 a les 11 33 43" src="https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/109797/a6eee366-db78-454b-bbde-381414401c11">

I checked the related Awesome settings and I didn't found any option to fix this
<img width="1356" alt="Captura de Pantalla 2024-04-10 a les 19 15 00" src="https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/109797/aac7df72-764a-43ac-8126-ab1edb05feb3">

**To Reproduce**
1. Go to '[proposal component settings](https://decidim-awesome.dev.pokecode.net/admin/participatory_processes/pressupost-participatiu/components/3/edit)'
2. Scroll down to 'Ordre de propostes per defecte'
3. See error

**Expected behavior**
Be able to define default full options to sort proposals by (recent, etc...)

**Comment by aramollis** [comment]
@entantoencuanto said:
I've been taking a look to decidim awesome and it seems that the feature forces the available default options to the ones defined by the module, and they can't coexist with the default sort options defined by Decidim

In [/lib/decidim/decidim_awesome/awesome.rb](https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/2a34c57248150d7c7eae77bd1ba7c64f211d60b7/lib/decidim/decidim_awesome/awesome.rb#L275-L281):

```
    def self.possible_additional_proposal_sortings
      @possible_additional_proposal_sortings ||= additional_proposal_sortings.to_a.filter_map do |sort|
        next unless sort.to_sym.in?([:az, :za, :supported_first, :supported_last])


        sort.to_s
      end
    end
```
This method rejects any option different from the 4 defined by the module. I don't know the reason, but it seems that the only way to have the old sorting options is to disable the feature from an initializer in the application

**Comment by aramollis** [comment]
I suggest, I understand this feature should:
- List also the default sort options defined by Decidim in order to leave or not
- If scope is defined as "Never" any restriction/change should be applied to default sort options defined by Decidim

Are you agree @microstudi @entantoencuanto ?

**Comment by aramollis** [comment]
After this [PR](https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/306) the default order options come back in the component settings and in frontend "order by".

But there is still an inconsistency btw additional options defined in Awesome settings and those additional shown in components settings.

- If you define in Awesome only "Z-A" as additional to apply everywhere, in the front "order by" is showing ok, but in components settings all 4 additional options are "available" in the select for "default order" field.

**Comment by microstudi** [comment]
@aramollis is this happening in version 0.27 too?

**Comment by aramollis** [comment]
> @aramollis is this happening in version 0.27 too?

I don't know

**Comment by microstudi** [comment]
I've merged the fix, if you confirm its's fixed you can close this!
