### ISSUE TITLE
 Image upload not working in the front office for fields created with custom proposal fields 

### ISSUE THREAD

**Issue by simonaszilinskas** [decidim-ice/decidim-module-decidim_awesome#297]
**Describe the bug**
The image upload functionality via the rich text editor in the front-office for custom proposal fields created via Decidim Awesome does not work. 

**To Reproduce**
1. Go to a platform with custom proposal fields + rich text editor enabled and applied;
2. Click on New Proposal and try to add an image to one of the custom proposal fields
3. Publish the proposal
4. Once published, the picture does not appear. 

**Expected behavior**
The image upload should work the same way for proposals created from the front office as it does for official proposals created from the Back Office. Images added to proposals created from the Front Office should properly appear once the proposal is published.

**Screenshots**
From the BO : the module is working well : 
![Untitled (27)](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/14858948/fe4fda6a-2d6e-489d-825b-bf1081f621f2)
But for proposals added from the F.O, it does not work : 

Step 1 : During the publication, the picture is correctly added :

![Untitled (28)](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/14858948/e21a0659-c199-4d74-a5a0-b65aa6d603bb)

Step 2 : But once published, the picture does not appear 
![Untitled (29)](https://github.com/decidim-ice/decidim-module-decidim_awesome/assets/14858948/b365f149-2853-4c20-adb9-d51b7eb9e07d)

**Additional context**
The custom field image upload work well from the back office.

Tested and error found on:
- Decidim Version: 0.26.7 and 0.27.4

**Comment by microstudi** [comment]
Note that this is still happening in version 0.28.
Also the preview page before publishing is affected.

**Comment by paarals** [comment]
this issue was funded by OpenSourcePolitics
